/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Services2RouteImport } from './routes/services2'
import { Route as Contact2RouteImport } from './routes/contact2'
import { Route as About2RouteImport } from './routes/about2'
import { Route as IndexRouteImport } from './routes/index'

const Services2Route = Services2RouteImport.update({
  id: '/services2',
  path: '/services2',
  getParentRoute: () => rootRouteImport,
} as any)
const Contact2Route = Contact2RouteImport.update({
  id: '/contact2',
  path: '/contact2',
  getParentRoute: () => rootRouteImport,
} as any)
const About2Route = About2RouteImport.update({
  id: '/about2',
  path: '/about2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about2': typeof About2Route
  '/contact2': typeof Contact2Route
  '/services2': typeof Services2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about2': typeof About2Route
  '/contact2': typeof Contact2Route
  '/services2': typeof Services2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about2': typeof About2Route
  '/contact2': typeof Contact2Route
  '/services2': typeof Services2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about2' | '/contact2' | '/services2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about2' | '/contact2' | '/services2'
  id: '__root__' | '/' | '/about2' | '/contact2' | '/services2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  About2Route: typeof About2Route
  Contact2Route: typeof Contact2Route
  Services2Route: typeof Services2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services2': {
      id: '/services2'
      path: '/services2'
      fullPath: '/services2'
      preLoaderRoute: typeof Services2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact2': {
      id: '/contact2'
      path: '/contact2'
      fullPath: '/contact2'
      preLoaderRoute: typeof Contact2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about2': {
      id: '/about2'
      path: '/about2'
      fullPath: '/about2'
      preLoaderRoute: typeof About2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  About2Route: About2Route,
  Contact2Route: Contact2Route,
  Services2Route: Services2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
